# workflow name 随便给自己的任务起个名
name: ablesci-checkin
# trigger  什么时候触发这个任务
on:
  workflow_dispatch: #手动执行
  schedule:          # 定时任务
    - cron:  43 * * * *   #想要运行的小时-8即为填入值例如：bj11点运行 填11-8=3
jobs:
  checkin:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Checkin
      run: |
        python3 ./ablesci.py    #要执行的py代码
      env: #设置secrets的环境变量
        ABLESCICOOKIE: ${{ secrets.ABLESCICOOKIE }}
        XZKEY: ${{ secrets.XZKEY }}